version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
  pre_build:
    commands:
      - python -m venv ~/.venv
      - source ~/.venv/bin/activate
      - make install

  build:
    commands:
      - make lint

artifacts:
  files:
    - application.py
    - requirements.txt
  name: flask-codepipeline-elastic-beanstalk-$(date +%Y-%m-%d)
